### DISCUSSION TITLE
application.properties / application.yml

### DISCUSSION THREAD

**Discussion by nhkiiim** [nhkiiim/TIL#12] [Spring]
__(1) application.properties__
- Key-Value 형식을 사용하여 외부 구성의 속성을 설정
```
spring.datasource.url=jdbc:h2:DB이름
spring.datasource.username=유저이름
spring.datasource.password=비밀번호
```

__(2) application.yml__
- YAML기반으로 외부 구성의 속성을 설정
```
spring:
    datasource:
        url: jdbc:h2:DB이름
        username: 유저이름
		password: 비밀번호
```
