### DISCUSSION TITLE
Kubernetes Ingress

### DISCUSSION THREAD

**Discussion by nhkiiim** [nhkiiim/TIL#203] [Infra]
### Ingress
> https://kubernetes.io/docs/concepts/services-networking/ingress/
- 클러스터 내의 서비스에 대한 외부 접근을 관리하는 API 오브젝트로 일반적으로 HTTP를 관리
- 인그레스는 부하 분산, SSL 종료, 명칭 기반의 가상 호스팅을 제공 가능

> minimal-ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

**Comment by nhkiiim** [comment]
> 도메인 발급 후 DNS 연결에 사용

> ingress.yaml

```yaml
  - host: [도메인명]
    http:
      paths:
      - backend:
          serviceName: wasservice
          servicePort: 8091
        path: /

```

> Ingress 재기동

```
kubectl apply -f /home/ictdev/ingress.yaml
```
